### ISSUE TITLE
Unable to perform feed account for main-v2

### ISSUE THREAD

**Issue by Makalfo** [aave/aave-sandbox#4]
Unable to perform feed account for main-v2

1. Spin up main-v2 fork: ` npm run node:fork:main-v2`
2. Attempt to feed the account with the balances: `npm run feed-accounts:main-v2 -- --accounts 0x976EA74026E726554dB657fA54763abd0C3a0aa9`

Error:
```Balances slot not found for 0xD46bA6D942050d489DBd938a2C909A5d5039A161
[warning] balance storage layout not found for [
  'AMPL',
  '0xD46bA6D942050d489DBd938a2C909A5d5039A161',
  symbol: 'AMPL',
  tokenAddress: '0xD46bA6D942050d489DBd938a2C909A5d5039A161'
]
- Succesfully changed the balance of input addresses to:
An unexpected error occurred:

Error: cannot find artifact "IERC20DetailedBytes"
    at Object.getArtifact (/com.docker.devenvironments.code/node_modules/hardhat-deploy/src/DeploymentsManager.ts:213:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getContract (/com.docker.devenvironments.code/helpers/utils.ts:30:20)
    at async getTokenSymbol (/com.docker.devenvironments.code/helpers/utils.ts:183:33)
    at async /com.docker.devenvironments.code/helpers/utils.ts:218:15
```
Expected: Fed Accounts with no errors

**Comment by kartojal** [comment]
Could you try to use latest version? Them compile the contracts to create the artifacts.
```
npm run compile

npm run node: fork:main-v2

npm run feed-accounts:main-v2 -- --accounts 0x976EA74026E726554dB657fA54763abd0C3a0aa9
```

**Comment by A-ndy-git** [comment]
Updating the package version alone should resolve this issue.

It is also worth noting `npm run compile` is unnecessary as it gets called within `npm run node:fork:main-v2`.

`package.json`:
```
{
     "node:fork:main-v2": "MARKET=main-v2 npm run node:eth",
     "node:eth": "npm run compile && env-cmd --use-shell \"npm run node:eth:subtask\""
}
```

**Comment by kartojal** [comment]
Closing due this should be fixed, @Makalfo let us know if there is any other problem.
