### ISSUE TITLE
Unable to perform feed account for main-v2

### ISSUE THREAD

**Issue by A-ndy-git** [aave/aave-sandbox#6]
EDIT 1 -> May be related to #4 . I saw the same error, however, after updating, the below error took stage. 
EDIT 2 -> Appears to be a `Action cannot be performed because the reserve is frozen` error. See [https://docs.aave.com/developers/v/2.0/guides/troubleshooting-errors](url).

### **Description:**

Unable to perform feed account for main v2 via -> `npm run feed-market:main-v2`.

### **Logs Extract:**
```
Balances slot not found for 0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd
[warning] balance storage layout not found for [
  'GUSD',
  '0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd',
  symbol: 'GUSD',
  tokenAddress: '0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd'
]

Balances slot not found for 0xD5147bc8e386d91Cc5DBE72099DAC6C9b99276F5
[warning] balance storage layout not found for [
  'renFIL',
  '0xD5147bc8e386d91Cc5DBE72099DAC6C9b99276F5',
  symbol: 'renFIL',
  tokenAddress: '0xD5147bc8e386d91Cc5DBE72099DAC6C9b99276F5'
]

Balances slot not found for 0xD46bA6D942050d489DBd938a2C909A5d5039A161
[warning] balance storage layout not found for [
  'AMPL',
  '0xD46bA6D942050d489DBd938a2C909A5d5039A161',
  symbol: 'AMPL',
  tokenAddress: '0xD46bA6D942050d489DBd938a2C909A5d5039A161'
]

- Faucet ERC20 reserves to users

An unexpected error occurred:

ProviderError: Error: VM Exception while processing transaction: reverted with reason string '3'
    at HttpProvider.request (/Users/**USERNAME_REDACTED**/Documents/aave-sandbox/node_modules/hardhat/src/internal/core/providers/http.ts:74:19)
    at HDWalletProvider.request (/Users/**USERNAME_REDACTED**/Documents/aave-sandbox/node_modules/hardhat/src/internal/core/providers/accounts.ts:188:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EthersProviderWrapper.send (/Users/**USERNAME_REDACTED**/Documents/aave-sandbox/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

Can anyone please assist in shedding some light on potential causes?

Many thanks!

**Comment by A-ndy-git** [comment]
Thanks very much @defispartan for your comments. Can confirm this lead me to resolution. Much appreciated.

For anyone that stumbles upon this in the short-term, the array of assets can be fixed with something like:

```
[
      [ "USDT", "0xdAC17F958D2ee523a2206206994597C13D831ec7" ], 
      [ "WBTC", "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599" ]
]
```

Then simply reflect this in the `borrowableAssetsList` variable:

`const borrowableAssetsList = [ "USDT" ];`

Many Thanks!
